image: node

pages:
  stage: deploy
  script:
  - npm install
  - ./node_modules/react-scripts/bin/react-scripts.js build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public 
  only:
  - master 
